AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Resources:
  MyLambdaFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: cloudresume-sam-test-api  # Replace with your existing Lambda function name
      Handler: lambda_function.lambda_handler  # Update with the correct handler for Python
      Runtime: python3.12  # Update to the appropriate Python version
      CodeUri: ./lambda-function
      Role: arn:aws:iam::664038053552:role/service-role/cloudresume-test-api-role-yzzna79h  # Replace with your existing Lambda execution role ARN

  # MyDynamoDBTable:
  #   Type: 'AWS::DynamoDB::Table'
  #   Properties:
  #     TableName: VisitorCounter-sam-test  # Replace with your existing DynamoDB table name
  #     AttributeDefinitions:
  #       - AttributeName: id
  #         AttributeType: S
  #       - AttributeName: visits
  #         AttributeType: N
  #     KeySchema:
  #       - AttributeName: id
  #         KeyType: HASH
  #     BillingMode: PAY_PER_REQUEST # Set BillingMode to PAY_PER_REQUEST for on-demand capacity
